
server:
  port: 8090

jwt:
  secret: SecretKeyWERTYuiopdfghjkERTYUetyuiogjWDFGHj2345
  expirationMs: 86400000

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 5 # 最小空闲时间
      idle-timeout: 600000 # 空闲连接存活最大时间，默认是 60 00 00 ，也就是 10 分钟
      maximum-pool-size: 10 #连接池最大连接数 默认是 10
      auto-commit: true # 自动提交
      max-lifetime: 1800000 # 连接池连接的最大生命周期
      connection-timeout: 30000 # 连接查实的时间 默认 30 秒